# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62aa381564a68dd18dfd42ecea8c87d0addbb0bed2a3863d427f5d949f2ce8eb5b4b9bcdbfbaebcc41a3d79fae7dff21fc36880df20d11fbc6d4889bb618ad4b

test:
  secret_key_base: eea1e2c9dc190635c4e60b7bb152a89f99fd684cb1f140be85807349df1635a099a838ff01f8b000726282a28210220ef2f10fbb297c457eb58dd55dc241e910

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
